### ISSUE TITLE
heatmap

### ISSUE THREAD

**Issue by rgarcia-herrera** [CSB-IG/rnw#20]

**Comment by AngelCampos** [comment]
Qué queremos que nos diga el heatmap? Niveles de expresión con TODOS los genes?? o cortamos con un treshhold de diferencialmente expresados?? 
Podríamos también adoptar algún método de análisis de vías para disminuir el numero de variables del output y facilitar la interpretación.

¿Qué tienen en mente?

**Comment by hachepunto** [comment]
No, un heatmap sirve más si es solo de los genes diferencialmente expresados.

**Comment by rgarcia-herrera** [comment]
El threshold se me hace buena idea, y podría ser un argumento del script, con un valor default.

**Comment by guillermodeandajauregui** [comment]
Valor default no treshold, pero si como argumento. Also, gene heatmap
primero. Uno de pathways es otro boleto más tardío.

**Comment by AngelCampos** [comment]
Ok. Entonces podría ser para que trabaje así:
1. Con una matriz de expresión de genes, ordenados por niveles de expresión diferencial
2. Que tome un threshold de sub y sobre expresados
3. y que etiquete casos y controles.

**Comment by AngelCampos** [comment]
Si pueden darle una checada al código y darme retroalimentación estaría chico porfa  También creó que el módulo de Expresión Diferencial debe estar, para saber exactamente como serían los archivos de entrada para el heatmap.
