### ISSUE TITLE
Normalización intralote

### ISSUE THREAD

**Issue by hachepunto** [CSB-IG/rnw#3]
Recibe un lote de CEL files del mismo experimento.
Regresa una matriz de expresión normalizada.
Verifica:
- Misma plataforma de chip

**Comment by rgarcia-herrera** [comment]
De cómo crear interfaces de línea de comando en R:

http://cran.r-project.org/web/packages/argparse/index.html

**Comment by hachepunto** [comment]
rgarcía dice que el reporte que añadí no va. Pero yo creo que es justo el momento para hacerlo. El pedirlo después implicaría doble esfuerzo para generar las gráficas. Yo propongo poner una opción "¿Quieres reporte?".
